### ISSUE TITLE
Bug with Plets

### ISSUE THREAD

**Issue by Supadog** [Supadog/DB_iti#115]
When you select one semester from STL and one from MMF, the wrong degree name is printed.

**Comment by GediminasDun** [comment]
Same happens if you select one SG semester and one MMF, I have checked this with BEGLIN Aoife.

Best regards,
Gediminas Dundulis
IT administrator at ITI
 
+43 664 88522 686
gediminasdundulis@gmail.com
g.dundulis@iti.ac.at
serviceadmin@iti.ac.at
